services:
  web:
    build: .
    # command: >
    #   sh -c "python periwinkleposts/manage.py migrate &&
    #          gunicorn --workers=2 --bind 0.0.0.0:8000 periwinkleposts.wsgi:application"
    command: >
        sh -c "python periwinkleposts/manage.py migrate &&
              gunicorn periwinkleposts.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --timeout 120"


    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
    - ./periwinkleposts/media:/app/periwinkleposts/media  #keep media files around after restarts

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hello_django -d hello_django -h localhost -p 5432"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  caddy:
      image: caddy:latest
      container_name: caddy
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - web
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  postgres_data:


