services:
  web:
    build: .
    # command: >
    #   sh -c "python periwinkleposts/manage.py migrate &&
    #          gunicorn --workers=2 --bind 0.0.0.0:8000 periwinkleposts.wsgi:application"
    command: >
        sh -c "python periwinkleposts/manage.py migrate &&
              gunicorn periwinkleposts.wsgi:application --bind 0.0.0.0:8000 --workers 2 --threads 4 --timeout 120"


    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  postgres_data:
