# Generated by Django 5.1.5 on 2025-02-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/fallback.png', upload_to=''),
        ),
    ]
