# Generated by Django 5.1.5 on 2025-03-08 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='local',
            field=models.BooleanField(default=True),
        ),
    ]
