# Generated by Django 5.1.5 on 2025-02-24 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authors_is_approved'),
        ('accounts', '0002_post_visibility'),
    ]

    operations = [
    ]
