# Generated by Django 5.1.5 on 2025-03-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authors_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
