# Generated by Django 5.1.5 on 2025-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_authors_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
