# Generated by Django 5.1.5 on 2025-02-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_authors_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='github_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
