# Generated by Django 5.1.5 on 2025-03-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_merge_0002_authors_is_approved_0002_post_visibility"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("require_approval", models.BooleanField(default=True)),
            ],
        ),
    ]
