# Generated by Django 5.1.5 on 2025-04-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post_image_url_alter_authors_displayname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.CharField(default=None, max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='page',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
