# Generated by Django 5.1.5 on 2025-02-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_followrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
