# Generated by Django 5.1.5 on 2025-02-15 06:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_authors_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
