# Generated by Django 5.1.5 on 2025-02-15 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_id_authors_row_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='row_id',
            new_name='id',
        ),
    ]
