# Generated by Django 5.1.5 on 2025-02-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_row_id_authors_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='id',
            new_name='row_id',
        ),
    ]
