# Generated by Django 5.1.5 on 2025-02-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_id_authors_row_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='id',
            field=models.CharField(default='set_default', max_length=100),
            preserve_default=False,
        ),
    ]
