# Generated by Django 5.1.5 on 2025-02-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_authors_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='host',
            field=models.CharField(default='http://', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
