# Generated by Django 5.1.5 on 2025-02-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_authors_host_alter_authors_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='id',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
