# Generated by Django 5.1.5 on 2025-02-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_authors_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='displayName',
            field=models.CharField(default='John Doe', max_length=200),
        ),
    ]
