# Generated by Django 5.1.5 on 2025-02-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_authors_displayname'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(('follower', models.F('followee')), _negated=True), name='prevent_self_follow'),
        ),
        migrations.AddConstraint(
            model_name='followrequest',
            constraint=models.CheckConstraint(condition=models.Q(('requester', models.F('requestee')), _negated=True), name='prevent_self_follow_request'),
        ),
    ]
