# Generated by Django 5.1.5 on 2025-03-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalNode',
            fields=[
                ('nodeURL', models.URLField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('team_name', models.CharField(max_length=40)),
            ],
        ),
    ]
