name: Run Django Tests
on: [push]

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Stable Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version  # Debugging: Check installed version

      - name: Install Matching ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d. -f1-3)
          echo "Detected Chrome version: $CHROME_VERSION"
          CHROMEDRIVER_URL="https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip"
          echo "Downloading ChromeDriver from: $CHROMEDRIVER_URL"
          
          wget -q "$CHROMEDRIVER_URL" -O chromedriver_linux64.zip || echo "ChromeDriver download failed!"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          chromedriver --version  # Debugging: Check installed version

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Tests with Headless Chrome
        run: |
          cd periwinkleposts
          Xvfb :99 -screen 0 1920x1080x24 &
          export DISPLAY=:99
          python3 manage.py test
