name: Run Django Tests
on:
  push:
    branches:
      - main  # Only run when pushing to the main branch

jobs:
  test_project:
    runs-on: ubuntu-latest  # Operating system to run the tests on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt  # Install dependencies
      - run: |
          cd periwinkleposts  # Navigate to the project folder
          python3 manage.py migrate
          python3 manage.py makemigrations
          python3 manage.py test  # Run Django tests
