name: Run Django Tests and Update Deployment
on:
  push:
    branches:
      - main  # Only run when pushing to the main branch
      - end_point_cleanup

jobs:
  test_project:
    runs-on: ubuntu-latest  # Operating system to run the tests on
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt  # Install dependencies
      - run: |
          cd periwinkleposts  # Navigate to the project folder
          python3 manage.py migrate
          python3 manage.py makemigrations
          python3 manage.py test  # Run Django tests

  build_and_push:
    needs: test_project  # Run only if tests pass
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "ryankennethrom" --password-stdin

      - name: Build Docker image
        run: docker build -t ryankennethrom/periwinkle:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ryankennethrom/periwinkle:latest
