name: Run Django Tests
on: [push]  # Activates the workflow on push or pull request

jobs:
  test_project:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensure the latest checkout action version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Adjust based on your project

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install Django and dependencies
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb  # Install Chrome and Xvfb

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: 'latest'  # Ensure ChromeDriver matches Chrome

      - name: Run Tests with Headless Chrome
        run: |
          cd periwinkleposts  # Change directory to project
          Xvfb :99 -screen 0 1920x1080x24 &  # Start a virtual display for GUI-based tests
          export DISPLAY=:99  # Set display for headless tests
          python3 manage.py test  # Run Django tests